### ISSUE TITLE
Consider the usage of further eslint plugins

### ISSUE THREAD

**Issue by mhatvan** [sveltejs/eslint-config#18]
There are two eslint plugins that I can highly recommend for improving code quality. They can be easily extended with a recommended config and adapted to one's needs:

- https://github.com/sindresorhus/eslint-plugin-unicorn
- https://github.com/xjamundx/eslint-plugin-promise

**Comment by benmccann** [comment]
I don't think we'd want to start from someone else's config. we're already pretty settled on the one we have and aren't going to introduce tons of rules without individually considering them. we'd just want to introduce one rule at a time

**Comment by mhatvan** [comment]
You are already starting off someone else's config ->  `eslint`, `eslint-plugin-import` and `@typescript-eslint` are extended and then just various rules disabled/modified. The same thing could be done for the two plugins I mentioned.

**Comment by benmccann** [comment]
The point though is that we're pretty happy with the current config. We're not going to be making massive unspecified changes to it. I have no idea what those plugins would change. If there are particular rules that are valuable happy to discuss them individually
