### ISSUE TITLE
Deprecation of stylistic rules

### ISSUE THREAD

**Issue by jrmajor** [sveltejs/eslint-config#32]
We use `quotes` and `quote-props` rules, which were deprecated in ESLint v8.53, among other stylistic rules.

> All of these rules will be deprecated as of the next release, but will not be removed until at least ESLint v10.0.0 (if not later). You can continue to use them although you may see deprecation warnings in the ESLint CLI.

Do we want to ignore this for now, drop this rules from our config, or require them via [`@stylistic/eslint-plugin`](https://eslint.style/guide/why)?

The third option would probably require a major version bump, since it adds a new peer dependency, so it may worth be doing before releasing #31, which also contains breaking changes.

**Comment by benmccann** [comment]
Let's get them from the plugin. It's fine to add a peer dep

**Comment by jrmajor** [comment]
OK, I'll follow up with a PR after #31 is merged.
