### ISSUE TITLE
Disallow unused variables

### ISSUE THREAD

**Issue by ehrencrona** [sveltejs/eslint-config#9]
Disallow unused variables.

**Describe the reason for the rule**
Unused variables can indicate bugs and dead code.

They should be allowed in function declarations where they can help clarify what parameters are expected. This can be done through

```'@typescript-eslint/no-unused-vars': ['error', { args: 'none' }]```

There is ~only a single~ no instance in the code where I would say the error is inappropriate ~(in an array destructuring along the lines of `const [_, myVar] = array`)~ (as antony pointed out below, there are better ways of writing this)

**Examples**
Please include an example of a block of code:
  1. with your suggested rule
  1. without your suggested rule

<img width="1119" alt="Screen Shot 2020-10-01 at 11 18 31 AM" src="https://user-images.githubusercontent.com/1862212/94791425-fc2d8800-03ad-11eb-8a99-d237972d5e5c.png">

**Poll**

[![](https://api.gh-polls.com/poll/01EKHQBGK8446JAQNATHYCSKQD/Allow%20unused%20vars)](https://api.gh-polls.com/poll/01EKHQBGK8446JAQNATHYCSKQD/Allow%20unused%20vars/vote)
[![](https://api.gh-polls.com/poll/01EKHQBGK8446JAQNATHYCSKQD/Do%20not%20allow%20unused%20vars)](https://api.gh-polls.com/poll/01EKHQBGK8446JAQNATHYCSKQD/Do%20not%20allow%20unused%20vars/vote)

**Comment by antony** [comment]
Just fyi, in your array example, you don't need to bypass this rule:

```
const [ , myVar ] = array
```

is how I do it.

**Comment by antony** [comment]
Those who voted for allow - since it's a pretty close tie - why did you vote for allow? what use are the unused variables?

**Comment by dummdidumm** [comment]
I vote for this rule with the given exception. I sometimes find it better to know what the unused variable is in a destructuring.

**Comment by antony** [comment]
@ehrencrona lets do this thing. Do you have a PR?

**Comment by ehrencrona** [comment]
I created one. The `svelte` projects has one warning after this rule is applied; I'll create a PR for that. The `sapper` project does not have any warnings. I can't find any other projects that use these settings.

**Comment by benmccann** [comment]
Those are the only two projects to worry about
